include:
  - path: ../synapse/docker-compose.yml

services:
  # ── Echo Bot (Appservice) ───────────────────────────────
  bot:
    build:
      context: ../..
      dockerfile: examples/echo_bot/Dockerfile
    restart: unless-stopped
    environment:
      APPSERVICE_CONFIG: examples/echo_bot/config/appservice.yml
    depends_on:
      synapse:
        condition: service_healthy
    ports:
      - 9292:9292
