# frozen_string_literal: true

# /_matrix/client/v3/account
module MatrixApi
  module Client
    module V3
      class Account < Base
        # GET /account/whoami
        # Auth: yes | Rate-limited: yes
        # Response: 200, 401, 403, 429
        desc 'Get information about the owner of an access token.' do
          detail 'Gets information about the owner of a given access token.'
          failure [
            [401, 'Unauthorized (M_UNKNOWN_TOKEN, M_MISSING_TOKEN)'],
            [403, 'Forbidden'],
            [429, 'Rate limited (M_LIMIT_EXCEEDED)']
          ]
        end
        get :whoami do
          authenticate!
          rate_limit!
          # TODO: implement
          status 200
        end

        # POST /account/password
        # Auth: optional | Rate-limited: yes | UIA
        # Response: 200, 401, 429
        namespace :password do
          desc 'Change the password for the current user.' do
            detail 'Changes the password for an account on this homeserver.'
            failure [
              [401, 'Unauthorized / UIA required'],
              [429, 'Rate limited (M_LIMIT_EXCEEDED)']
            ]
          end
          params do
            requires :new_password, type: String, desc: 'The new password'
            optional :logout_devices, type: Boolean, default: true, desc: 'Logout all other devices'
            optional :auth, type: Hash, desc: 'User-Interactive Authentication data'
          end
          post do
            rate_limit!
            # TODO: implement
            status 200
          end

          # POST /account/password/email/requestToken
          # Auth: no | Rate-limited: no
          # Response: 200, 400, 403
          namespace :email do
            desc 'Request email token for password reset.' do
              failure [
                [400, 'Bad request (M_THREEPID_NOT_FOUND, M_SERVER_NOT_TRUSTED)'],
                [403, 'Forbidden']
              ]
            end
            params do
              requires :client_secret, type: String, desc: 'A unique string generated by the client'
              requires :email, type: String, desc: 'The email address'
              requires :send_attempt, type: Integer, desc: 'Attempt count'
              optional :next_link, type: String, desc: 'URL to redirect to after validation'
              optional :id_server, type: String, desc: 'Identity server hostname'
              optional :id_access_token, type: String, desc: 'Identity server access token'
            end
            post :requestToken do
              # TODO: implement
              status 200
            end
          end

          # POST /account/password/msisdn/requestToken
          # Auth: no | Rate-limited: no
          # Response: 200, 400, 403
          namespace :msisdn do
            desc 'Request phone token for password reset.' do
              failure [
                [400, 'Bad request'],
                [403, 'Forbidden']
              ]
            end
            params do
              requires :client_secret, type: String, desc: 'A unique string generated by the client'
              requires :country, type: String, desc: 'ISO 3166-1 alpha-2 country code'
              requires :phone_number, type: String, desc: 'The phone number'
              requires :send_attempt, type: Integer, desc: 'Attempt count'
              optional :next_link, type: String, desc: 'URL to redirect to after validation'
              optional :id_server, type: String, desc: 'Identity server hostname'
              optional :id_access_token, type: String, desc: 'Identity server access token'
            end
            post :requestToken do
              # TODO: implement
              status 200
            end
          end
        end

        # POST /account/deactivate
        # Auth: optional | Rate-limited: yes | UIA
        # Response: 200, 401, 429
        desc 'Deactivate the user account.' do
          detail 'Deactivates the user\'s account, removing all ability to login again.'
          failure [
            [401, 'Unauthorized / UIA required'],
            [429, 'Rate limited (M_LIMIT_EXCEEDED)']
          ]
        end
        params do
          optional :auth, type: Hash, desc: 'User-Interactive Authentication data'
          optional :id_server, type: String, desc: 'Identity server to unbind from'
          optional :erase, type: Boolean, default: false, desc: 'Erase user data (added v1.10)'
        end
        post :deactivate do
          rate_limit!
          # TODO: implement
          status 200
        end

        # ======================================================================
        # 3PID Management - /account/3pid/*
        # ======================================================================
        namespace '3pid' do
          # GET /account/3pid
          # Auth: yes | Rate-limited: no
          # Response: 200
          desc 'Get a list of third-party identifiers for the user.'
          get do
            authenticate!
            # TODO: implement
            status 200
          end

          # POST /account/3pid (deprecated)
          # Auth: yes | Rate-limited: no
          # Response: 200, 403
          desc 'Add 3PID to the user account (deprecated).' do
            failure [[403, 'Forbidden']]
          end
          params do
            requires :three_pid_creds, type: Hash, desc: 'Third-party credentials' do
              requires :client_secret, type: String
              requires :id_server, type: String
              requires :id_access_token, type: String
              requires :sid, type: String
            end
          end
          post do
            authenticate!
            # TODO: implement
            status 200
          end

          # POST /account/3pid/add
          # Auth: yes | Rate-limited: yes | UIA
          # Response: 200, 401, 429
          desc 'Add a 3PID to the user account.' do
            failure [
              [401, 'Unauthorized / UIA required'],
              [429, 'Rate limited (M_LIMIT_EXCEEDED)']
            ]
          end
          params do
            optional :auth, type: Hash, desc: 'User-Interactive Authentication data'
            requires :client_secret, type: String, desc: 'Client secret from the requestToken call'
            requires :sid, type: String, desc: 'Session ID from the requestToken call'
          end
          post :add do
            authenticate!
            rate_limit!
            # TODO: implement
            status 200
          end

          # POST /account/3pid/bind
          # Auth: yes | Rate-limited: yes
          # Response: 200, 429
          desc 'Bind a 3PID to an identity server.' do
            failure [[429, 'Rate limited (M_LIMIT_EXCEEDED)']]
          end
          params do
            requires :client_secret, type: String, desc: 'Client secret'
            requires :id_server, type: String, desc: 'Identity server hostname'
            requires :id_access_token, type: String, desc: 'Identity server access token'
            requires :sid, type: String, desc: 'Session ID'
          end
          post :bind do
            authenticate!
            rate_limit!
            # TODO: implement
            status 200
          end

          # POST /account/3pid/delete
          # Auth: yes | Rate-limited: no
          # Response: 200
          desc 'Remove a 3PID from the user account.'
          params do
            requires :medium, type: String, values: %w[email msisdn], desc: 'The medium of the 3PID'
            requires :address, type: String, desc: 'The third-party address'
            optional :id_server, type: String, desc: 'Identity server to unbind from'
          end
          post :delete do
            authenticate!
            # TODO: implement
            status 200
          end

          # POST /account/3pid/unbind
          # Auth: yes | Rate-limited: no
          # Response: 200
          desc 'Unbind a 3PID from an identity server.'
          params do
            requires :medium, type: String, values: %w[email msisdn], desc: 'The medium of the 3PID'
            requires :address, type: String, desc: 'The third-party address'
            optional :id_server, type: String, desc: 'Identity server to unbind from'
          end
          post :unbind do
            authenticate!
            # TODO: implement
            status 200
          end

          # POST /account/3pid/email/requestToken
          # Auth: no | Rate-limited: no
          # Response: 200, 400, 403
          namespace :email do
            desc 'Request email token for 3PID addition.' do
              failure [
                [400, 'Bad request (M_THREEPID_IN_USE, M_SERVER_NOT_TRUSTED)'],
                [403, 'Forbidden']
              ]
            end
            params do
              requires :client_secret, type: String
              requires :email, type: String
              requires :send_attempt, type: Integer
              optional :next_link, type: String
              optional :id_server, type: String
              optional :id_access_token, type: String
            end
            post :requestToken do
              # TODO: implement
              status 200
            end
          end

          # POST /account/3pid/msisdn/requestToken
          # Auth: no | Rate-limited: no
          # Response: 200, 400, 403
          namespace :msisdn do
            desc 'Request phone token for 3PID addition.' do
              failure [
                [400, 'Bad request'],
                [403, 'Forbidden']
              ]
            end
            params do
              requires :client_secret, type: String
              requires :country, type: String
              requires :phone_number, type: String
              requires :send_attempt, type: Integer
              optional :next_link, type: String
              optional :id_server, type: String
              optional :id_access_token, type: String
            end
            post :requestToken do
              # TODO: implement
              status 200
            end
          end
        end # namespace 3pid
      end
    end
  end
end
