# frozen_string_literal: true

# /_matrix/client/v3/register
module MatrixApi
  module Client
    module V3
      class Register < Base
        # POST /register - Register a new user account
        # Auth: no | Rate-limited: yes | UIA (except guest)
        # Response: 200, 400, 401, 403, 429
        desc 'Register a new user account.' do
          detail 'Register for an account on this homeserver.'
          failure [
            [400, 'Bad request (M_USER_IN_USE, M_INVALID_USERNAME, M_EXCLUSIVE)'],
            [401, 'Unauthorized / UIA required'],
            [403, 'Forbidden'],
            [429, 'Rate limited (M_LIMIT_EXCEEDED)']
          ]
        end
        params do
          optional :kind, type: String, values: %w[guest user], default: 'user', desc: 'Account kind'
          optional :auth, type: Hash, desc: 'User-Interactive Authentication data'
          optional :username, type: String, desc: 'Desired username'
          optional :password, type: String, desc: 'Desired password'
          optional :device_id, type: String, desc: 'Device ID'
          optional :initial_device_display_name, type: String, desc: 'Device display name'
          optional :inhibit_login, type: Boolean, desc: 'If true, do not generate access token'
          optional :refresh_token, type: Boolean, desc: 'Request a refresh token'
        end
        post do
          rate_limit!
          # TODO: implement
          status 200
        end

        # GET /register/available - Check username availability
        # Auth: no | Rate-limited: yes
        # Response: 200, 400, 429
        desc 'Check if a username is available.' do
          detail 'Checks to see if a username is available and valid for the server.'
          failure [
            [400, 'Bad request (M_USER_IN_USE, M_INVALID_USERNAME, M_EXCLUSIVE)'],
            [429, 'Rate limited (M_LIMIT_EXCEEDED)']
          ]
        end
        params do
          requires :username, type: String, desc: 'The username to check'
        end
        get :available do
          rate_limit!
          # TODO: implement
          status 200
        end

        # POST /register/email/requestToken
        # Auth: no | Rate-limited: no
        # Response: 200, 400, 403
        namespace :email do
          desc 'Request email token for registration.' do
            detail 'Requests a validation token be sent to the given email for registration.'
            failure [
              [400, 'Bad request (M_THREEPID_IN_USE, M_SERVER_NOT_TRUSTED)'],
              [403, 'Forbidden (M_THREEPID_DENIED)']
            ]
          end
          params do
            requires :client_secret, type: String, desc: 'A unique string generated by the client'
            requires :email, type: String, desc: 'The email address to validate'
            requires :send_attempt, type: Integer, desc: 'Attempt count to prevent re-sends'
            optional :next_link, type: String, desc: 'URL to redirect to after validation'
            optional :id_server, type: String, desc: 'Identity server hostname (deprecated)'
            optional :id_access_token, type: String, desc: 'Identity server access token (deprecated)'
          end
          post :requestToken do
            # TODO: implement
            status 200
          end
        end

        # POST /register/msisdn/requestToken
        # Auth: no | Rate-limited: no
        # Response: 200, 400, 403
        namespace :msisdn do
          desc 'Request phone number token for registration.' do
            detail 'Requests a validation token be sent to the given phone number for registration.'
            failure [
              [400, 'Bad request (M_THREEPID_IN_USE, M_SERVER_NOT_TRUSTED)'],
              [403, 'Forbidden (M_THREEPID_DENIED)']
            ]
          end
          params do
            requires :client_secret, type: String, desc: 'A unique string generated by the client'
            requires :country, type: String, desc: 'ISO 3166-1 alpha-2 country code'
            requires :phone_number, type: String, desc: 'The phone number'
            requires :send_attempt, type: Integer, desc: 'Attempt count'
            optional :next_link, type: String, desc: 'URL to redirect to after validation'
            optional :id_server, type: String, desc: 'Identity server hostname (deprecated)'
            optional :id_access_token, type: String, desc: 'Identity server access token (deprecated)'
          end
          post :requestToken do
            # TODO: implement
            status 200
          end
        end
      end
    end
  end
end
